server:
  port: 80
spring:
  h2:
    console:
      enabled: true
  datasource1:
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    jdbc-url: jdbc:log4jdbc:mysql://localhost:3306/migration?serverTimezone=UTC&characterEncoding=UTF-8
    username: admin
    password: nimda
# h2
#    driver-class-name: org.h2.Driver
#    jdbc-url: jdbc:h2:mem:testdb
##    jdbc-url: jdbc:h2:file:C:/hs/h2
#    username: sa
#    password:
  datasource2:
# 오라클
#    driver-class-name: oracle.jdbc.driver.OracleDriver
#    jdbc-url: jdbc:oracle:thin:@127.0.0.1:1521:xe
#    username: SYS as sysdba
#    password: 1234
# mysql
#    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    jdbc-url: jdbc:log4jdbc:mysql://localhost:3306/handsome?serverTimezone=UTC&characterEncoding=UTF-8
    username: admin
    password: nimda

  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    hibernate:
      ddl-auto: create-drop #update #create-drop
    properties:
      hibernate:
        show_sql: false
        format_sql: true
#        globally_quoted_identifiers: true
#mybatis:
#  mapper-location: classpath:mapper/**/*.xml
#  configuration:
#    lazyLoadingEnabled=true
#    aggressiveLazyLoading=false
#    mapUnderscoreToCamelCase=true

logging:
  level:
    org.springframework : info
    sql: info
    jdbc:
      sqlonly: off
      sqltiming: off
      audit: off
      resultset: off
      resultsettable: off
      connection: off
    com.hansum.migration: debug
  file:
    name: C:/hs/log/migrationlog.log
#    name: /logs/migrationlog.log
    max-history: 9999999
    max-size : 500MB
  pattern:
    file: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
    rolling-file-name: C:/hs/log/migrationlog_%d{yyyy-MM-dd}.%i"
#    rolling-file-name: /logs/migrationlog_%d{yyyy-MM-dd}.%i"
# Mybatis
#  mybatis:
#    # mapper.xml 위치 지정
#    mapper-locations:
#    - mybatis-mapper/**/*.xml
#    # model 프로퍼티 camel case 설정
#    configuration:
#      map-underscore-to-camel-case: true
#    # 패키지명 생략할 수 있도록 alias 설정
#    type-aliases-package: com.hansum.migration
